<?xml version="1.0" encoding="UTF-8"?> 
<wsdl:definitions 
  name="GetMeterReadSchedule" 
  targetNamespace="http://iec.ch/TC57/2011/GetMeterReadSchedule" 
  xmlns:tns="http://iec.ch/TC57/2011/GetMeterReadSchedule" 
  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" 
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
  xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" 
  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
  xmlns:infoMessage="http://iec.ch/TC57/2011/GetMeterReadScheduleMessage">
  <wsdl:types>
    <xs:schema targetNamespace="http://iec.ch/TC57/2011/GetMeterReadSchedule"  elementFormDefault="qualified">
      <xs:import namespace="http://iec.ch/TC57/2011/GetMeterReadScheduleMessage" schemaLocation="xsd/GetMeterReadScheduleMessage.xsd"/>  
    </xs:schema> 
  </wsdl:types> 
  <!-- Message Definitions --> 
  <wsdl:message name="GetMeterReadScheduleRequestMessage">
    <wsdl:part name="GetMeterReadScheduleRequestMessage" element="infoMessage:GetMeterReadSchedule"/>
  </wsdl:message>  
  <wsdl:message name="ResponseMessage">
    <wsdl:part name="ResponseMessage" element="infoMessage:MeterReadScheduleResponseMessage"/>
  </wsdl:message>  
  <wsdl:message name="FaultMessage">
    <wsdl:part name="FaultMessage" element="infoMessage:MeterReadScheduleFaultMessage"/>
  </wsdl:message>  
  <!-- Port Definitions -->
  <wsdl:portType name="GetMeterReadSchedule_Port"> 
    <wsdl:operation name="GetMeterReadSchedule"> 
      <wsdl:input name="GetMeterReadScheduleRequest" message="tns:GetMeterReadScheduleRequestMessage"/> 
      <wsdl:output name="GetMeterReadScheduleResponse" message="tns:ResponseMessage"/> 
      <wsdl:fault name="GetMeterReadScheduleFault" message="tns:FaultMessage"/>
    </wsdl:operation>
  </wsdl:portType>  
  <wsdl:binding name="GetMeterReadSchedule_Binding" type="tns:GetMeterReadSchedule_Port">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/> 
    <wsdl:operation name="GetMeterReadSchedule">
      <soap:operation soapAction="http://iec.ch/TC57/2011/GetMeterReadSchedule/GetMeterReadSchedule" style="document"/> 
      <wsdl:input name="GetMeterReadScheduleRequest">  
        <soap:body use="literal"/> 
      </wsdl:input> 
      <wsdl:output name="GetMeterReadScheduleResponse">  
        <soap:body use="literal"/> 
      </wsdl:output> 
      <wsdl:fault name="GetMeterReadScheduleFault">  
        <soap:fault name="GetMeterReadScheduleFault" use="literal"/> 
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>  
  <wsdl:service name="GetMeterReadSchedule">
    <wsdl:port name="GetMeterReadSchedule_Port" binding="tns:GetMeterReadSchedule_Binding"> 
      <soap:address location="http://iec.ch/TC57/2011/GetMeterReadSchedule"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions> 
